name: Deploy to review1

on:
  push:
    branches:
      - review1

jobs:
  deploy-server:
    name: "Deploy server"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Set heroku production env to false
        run: heroku config:set NPM_CONFIG_PRODUCTION=false YARN_PRODUCTION=false -a ${{ secrets.HEROKU_REVIEW1_APP }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_REVIEW1_API_KEY }}
      - name: Deploy to heroku
        run: git push -f https://heroku:${{ secrets.HEROKU_REVIEW1_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_REVIEW1_APP }}.git review1:master
  
  deploy-webapp:
    name: "Deploy web client"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 'Build client'
        run: |
          cd webapp
          yarn
          yarn build
        env:
          VUE_APP_API_URL: https://${{ secrets.HEROKU_REVIEW1_APP }}.herokuapp.com/api
          VUE_APP_BASE_URL: https://${{ secrets.FIREBASE_REVIEW1_APP }}.web.app
          NODE_ENV: production
      - name: 'Deploy to firebase'
        run: |
          npm install -g firebase-tools
          cd webapp
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} -P ${{ secrets.FIREBASE_REVIEW1_APP }}
